### PR TITLE
Im/test on untiled galaxies + improve locs metric + binary tests

### PR DESCRIPTION
**Pull request by ismael-mendoza**

### CODE REVIEW

**Comment by ismael-mendoza** [comment]
passes stably on cpu + gpu is will close if passes on CI

**Comment by jeff-regier** [comment]
Does `test_galaxy_vae` pass for you? I'm getting

```
tests/test_galaxy_vae.py:41: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../miniconda3/envs/bliss/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:444: in fit
    results = self.accelerator_backend.train()
../../miniconda3/envs/bliss/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py:54: in train
    results = self.train_or_test()
../../miniconda3/envs/bliss/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py:68: in train_or_test
    results = self.trainer.train()
../../miniconda3/envs/bliss/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:466: in train
    self.run_sanity_check(self.get_model())
../../miniconda3/envs/bliss/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:658: in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
../../miniconda3/envs/bliss/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:566: in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
../../miniconda3/envs/bliss/lib/python3.8/site-packages/torch/utils/data/dataloader.py:435: in __next__
    data = self._next_data()
../../miniconda3/envs/bliss/lib/python3.8/site-packages/torch/utils/data/dataloader.py:475: in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
../../miniconda3/envs/bliss/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py:44: in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
../../miniconda3/envs/bliss/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py:44: in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
bliss/datasets/galaxy_datasets.py:56: in __getitem__
    "image": self.dset[idx],  # shape = (n_bands, slen, slen)
h5py/_objects.pyx:54: in h5py._objects.with_phil.wrapper
    ???
h5py/_objects.pyx:55: in h5py._objects.with_phil.wrapper
    ???
../../miniconda3/envs/bliss/lib/python3.8/site-packages/h5py/_hl/dataset.py:777: in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
../../miniconda3/envs/bliss/lib/python3.8/site-packages/h5py/_hl/selections.py:82: in select
    return selector.make_selection(args)
h5py/_selector.pyx:272: in h5py._selector.Selector.make_selection
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   TypeError: Simple selection can't process 638.0

h5py/_selector.pyx:213: TypeError
```

**Comment by ismael-mendoza** [comment]
Yeah it's passing for me. Did you update h5py to the lastest version? `h5py==2.10.0` ?

**Comment by jeff-regier** [comment]
That fixed it. I had version 3.1 installed before. Does one of our other dependencies not work with the latest h5py yet?

**Pull request merged**
