### PR TITLE
Probabilistic Tile Suppression

### PR DESCRIPTION
**Pull request by aakashdp6548**
This PR is part of a larger set of changes involving better handling for sources near tile boundaries (#806).

In particular, this PR adds basic infrastructure changes, like the RegionCatalog class and conversions between different types of catalogs.

I propose we let `RegionCatalog` inherit from `TileCatalog` for now, minimizing duplicated code. If we eventually decide to replace `TileCatalog` altogether, we can just move the necessary code over to `RegionCatalog`. Sources in a `RegionCatalog` currently work very similarly to `TileCatalog`. The locations are fractions of the region size in $[0, 1)^2$, but unlike the constant tile size in `TileCatalog`, the region size varies. The conversion between the internal location and the pixel coordinates is done by `RegionCatalog.get_full_locs_from_regions`, which multiplies the fraction by the region size and adds the offset.

### CODE REVIEW

**Comment by aakashdp6548** [comment]
TODOs for this PR:
- [ ] Add conversion from RegionCatalog to `TileCatalog`
- [ ] Update documentation for new functions and class
- [ ] Add tests for RegionCatalog, including conversion between catalogs with different batch sizes and max_sources

**Review by jeff-regier — APPROVED** [review]

**Comment by aakashdp6548** [comment]
@jeff-regier I think we're ready to merge this as a case study. Can you take another quick look at the changes outside of `region_catalog.py` and `region_encoder.py`? I made some small changes to plotting that will affect other stuff, but they should be pretty minor.

**Review by jeff-regier — APPROVED** [review]
Looks good!

**Comment by jeff-regier** [comment]
An isort error:
```
tests/test_catalogs.py:10:1: I001 isort found an import in the wrong position
```

**Comment by aakashdp6548** [comment]
Oops, not sure how that got missed by the precommit hook. Should be fixed now, will merge pended tests passing.

**Pull request merged**
