### PR TITLE
Enable binning by magnitude, keeping cuts as a special case

### PR DESCRIPTION
**Pull request by dereklhansen**

### CODE REVIEW

**Comment by ismael-mendoza** [comment]
Thanks! This is useful

**Comment by dereklhansen** [comment]
```
output/semisynthetic_figures
detections
           recall  expected_recall  precision  expected_precision    n
18       1.000000              NaN   1.000000                 NaN   22
19       0.993548              NaN   0.977273                 NaN  155
20       0.925781              NaN   0.960938                 NaN  256
21       0.881356              NaN   0.918919                 NaN  118
22       0.819048              NaN   0.846154                 NaN  105
23       0.621212              NaN   0.923077                 NaN   66
24       0.000000              NaN        NaN                 NaN    8
overall  0.871658         0.822218   0.922207            0.917945  748
accuracy
         class_acc  expected_accuracy  galaxy_accuracy  expected_galaxy_accuracy  star_accuracy  expected_star_accuracy    n
18        1.000000           0.999566              NaN                       NaN       1.000000                0.999566   22
19        1.000000           0.997745         1.000000                  0.997275       1.000000                0.999662  155
20        1.000000           0.998335         1.000000                  0.998142       1.000000                0.999791  256
21        1.000000           0.997603         1.000000                  0.996678       1.000000                0.999064  118
22        0.958904           0.958860         1.000000                  0.923263       0.955224                0.981840  105
23        1.000000           0.876678              NaN                       NaN       1.000000                0.876678   66
24             NaN                NaN              NaN                       NaN            NaN                     NaN    8
overall   0.984663           0.984215         0.994975                  0.989250       0.968504                0.975344  748

output/sdss_figures
detections
           recall  expected_recall  precision  expected_precision    n
18       0.937500              NaN   1.000000                 NaN   32
19       0.928571              NaN   0.800000                 NaN   56
20       0.976471              NaN   0.790123                 NaN   85
21       0.857955              NaN   0.838926                 NaN  176
22       0.623431              NaN   0.623824                 NaN  239
23       0.424779              NaN   0.454545                 NaN  113
24       0.000000              NaN        NaN                 NaN   17
overall  0.651475         0.618346   0.607417             0.85806  746
accuracy
         class_acc  expected_accuracy  galaxy_accuracy  expected_galaxy_accuracy  star_accuracy  expected_star_accuracy    n
18        1.000000           0.981856              NaN                  0.813269       1.000000                0.999602   32
19        1.000000           0.989452         1.000000                  0.979443       1.000000                0.994457   56
20        1.000000           0.977684         1.000000                  0.974637       1.000000                0.981896   85
21        0.943662           0.970482         0.903226                  0.963410       0.975000                0.982567  176
22        0.886792           0.903792         0.783784                  0.883299       0.942029                0.932450  239
23        0.965517           0.866771         0.000000                       NaN       1.000000                0.866771  113
24             NaN                NaN              NaN                       NaN            NaN                     NaN   17
overall   0.814815           0.927354         0.696850                  0.921454       0.943965                0.931987  746

output/simulated_figures
detections
           recall  expected_recall  precision  expected_precision     n
18       0.985507              NaN   0.981132                 NaN    69
19       0.928000              NaN   0.922397                 NaN  1125
20       0.848101              NaN   0.906789                 NaN  1975
21       0.705366              NaN   0.837161                 NaN  1025
22       0.646481              NaN   0.857678                 NaN   611
23       0.437681              NaN   0.711443                 NaN   345
24            NaN              NaN        NaN                 NaN     0
overall  0.785920         0.842276   0.875427            0.910042  5213
accuracy
         class_acc  expected_accuracy  galaxy_accuracy  expected_galaxy_accuracy  star_accuracy  expected_star_accuracy     n
18        1.000000           0.999602              NaN                       NaN       1.000000                0.999602    69
19        1.000000           0.992671         1.000000                  0.991749       1.000000                0.999511  1125
20        0.999217           0.984924         0.999100                  0.983692       1.000000                0.995300  1975
21        0.996063           0.965094         1.000000                  0.956852       0.990950                0.983346  1025
22        0.986577           0.939493         0.933333                  0.902685       0.989399                0.951947   611
23        1.000000           0.871148              NaN                       NaN       1.000000                0.871148   345
24             NaN                NaN              NaN                       NaN            NaN                     NaN     0
overall   0.979497           0.972837         0.988780                  0.977299       0.958233                0.961587  5213
```

**Comment by ismael-mendoza** [comment]
Thanks @dereklhansen - just to clarify the mag 18 on the leftmost column means objects with magnitude between [17, 18] ?

**Comment by dereklhansen** [comment]
The minimum flux for galaxies is 1000, which is a magnitude of 22.48. This translates to a low number of galaxies with magnitude above 21. Furthermore, look at the `simulated_figures` above for mag bin 22, which is what we train sleep phase on. Out of 611  total objects, only 171 (28%) are galaxies. Compared to the SDSS at the same mag_bin (239 total objects, 158 galaxies, 66%), this is a large misspecification

**Comment by jeff-regier** [comment]
Perhaps the star/galaxy prior is backwards? In the SDSS catalog about 28% of objects are stars and the other 72% are galaxies.

**Comment by jeff-regier** [comment]
These tables are quite informative and interesting. I'm particularly curious about why we aren't detecting ~7% of these bright objects:
```
18       0.937500              NaN   1.000000                 NaN   32          10
19       0.928571              NaN   0.800000                 NaN   56          29
```

**Pull request merged**
