### PR TITLE
try pareto as prior of galaxy fluxes

### LINKED ISSUE #333: Retrain on dimmer galaxies
I realized that there are basically no galaxies with mag > 19 on original simulated sample of galsim galaxies. We need to retrain including this dimmer galaxies so that we get better performance on the sdss chunk. Also this might solve the issue seen on the scatter bin plot (see below, top left panel) where our AE systematically overestimates fluxes for galaxies

- [x] Look at flux/mag distribution on SDSS catalog so we can try matching it.
- [x] Sample uniformly in magnitude between 16 - 21 ? Sample from magnitudes in the catalog? or some smooth interpolation? use a pareto distribution?
- [x] retrain now that #460 is merged and see if still see improvement
- [ ] retrain with pareto fluxes for galaxies
- [ ] make a scatter plot of matched galaxies/star in frame, BLISS magnitude vs PHOTO coadd magnitude. Should see improvement.
- [ ] check precision/recall. Also improvement? 
- [ ] do we still see systematic downward shift in magnitudes Individual galaxy residual? (remember to include outliers)
- [ ] also check ellipticity plot just in case

image

### PR DESCRIPTION
**Pull request by ismael-mendoza**
Closes #333 

- [x] #490 
- [ ] Sample HLR uniformly, then a/b
- [ ] Account for correlation between size and flux.
- [ ] in `plot_image_and_locs` should be explicit name variable `plocs` or just `locs`? (at least in arguments and docstring maybe?)

### CODE REVIEW

**Comment by ismael-mendoza** [comment]
After playing the truncated pareto for a bit this is how it compares with the SDSS catalog fluxes?
Do you have additional suggestions for making them the same @jeff-regier ?  Here is the funtion I used 

```
def pareto_sample(n, f_min=1e3, f_max=1e6, alpha=0.5, factor=2):
    u_max = 1 - (f_min / f_max) ** alpha
    uniform_samples = np.random.rand(n) * u_max
    return (f_min*factor) / (1.0 - uniform_samples) ** (1 / alpha)
```

Screen Shot 2022-03-02 at 9 49 26 AM
s

**Comment by jeff-regier** [comment]
This PR will help, you could try it. I suspect the lack of support below 3.25 flux (on your graph--not sure what the units are here) will be problematic. Not modeling the correlation between size and flux could also be problematic. Seems the simplest thing would be to use an empirical prior, perhaps with a bit of Gaussian noise added to it

**Comment by ismael-mendoza** [comment]
Thanks Jeff, another option is to sample directly from the coadd catalog. It would probably not be desirable to use coadd for the same frame we are predicting but if we could get coadds for other frames that would work.

**Comment by ismael-mendoza** [comment]
Here are some results on retraining the autoencoder on the pareto prior for galaxy fluxes 

image

image


Screen Shot 2022-03-07 at 10 44 20 PM

**Comment by ismael-mendoza** [comment]
Here are the most recent plots after retraining all the models with the pareto prior on galaxy fluxes specified above. We should probably discuss more before merging. Some observations: 

- The binary classification plot took a hit in galaxy accuracy, like 10% of galaxy accuracy was decreased. We should take a look at the confidence though.
- The precision curve is now better and without a dip. It remains constant before 22 magnitude which is interesting. I suspect though that we will see it increasing at high magnitude after masking the saturation. The recall curve remained unchanged so overall it looks like a good change for these curves. I think it might be worth examining by eye some of the previous detections we identified in #451 as false positives and see how this changed those. But also some of the detections we are missing still. 
- The SDSS reconstruction figures still look pretty good overall in terms of residuals, some classifications are more off compared to #425 but we should look at the confidence too.
- In one of the SDSS blends we now classify the object correctly as a galaxy (previously a star). These SDSS blends look basically unchanged. 
- The reconstruction of worst individual galaxies (second figure) suffered, which makes sense because we are no longer "over-training" on only bright galaxies. 
- You can see in the random reconstructions (first figure), that some galaxies are pretty much buried in the noise. They are indeed present in the SDSS sample in terms of their flux, but perhaps we should model the size correlation because some of the most extended ones will be completely invisible. The easiest way I can think of donig this is by matching quantiles between magnitude/flux and HLR which would be good enough I think. 
- The individual galaxy metrics look quite strange. With very faint objects I can see why ellipticity and size would be harder to estimate. Before our sample consistently almost exclusively of bright objects. Especially if trying to reconstrcut some of the "invisible" objects. You can see this in the last two plots. Another idea is to bin residual ellipticity errors by magnitude/SNR. 


random_reconstructions
worst_reconstructions
sdss_reconstruction0
sdss_reconstruction1
sdss_reconstruction2
sdss_reconstruction3
sdss-classification-acc
sdss-precision-recall
single_galaxy_measurements_contours
single_galaxy_scatter_bins

**Comment by ismael-mendoza** [comment]
One of the blends in #461 is now detected. The other ones are not. 

Screen Shot 2022-03-08 at 8 27 06 AM
Screen Shot 2022-03-08 at 8 30 06 AM
Screen Shot 2022-03-08 at 8 26 19 AM

**Comment by ismael-mendoza** [comment]
This figure is not very encouraging :/ 

Screen Shot 2022-03-08 at 8 49 40 AM

**Comment by jeff-regier** [comment]
Great work, Ismael.

It's fishy that three ~16 magnitude stars that are misclassified. Is that due to saturation? It'd be good to exclude any tiles that  are near saturated pixels. That may help with many of the misclassifications -- not just these three.

**Comment by ismael-mendoza** [comment]
Just to be clear, the results before this post are NOT with pareto distribution since we had to fix #490 first.

**Comment by dereklhansen** [comment]
@ismael-mendoza Can this be merged?

**Comment by ismael-mendoza** [comment]
Hi @dereklhansen - I guess this plot is the only thing I'm worried about which you confirm you saw in the VAE side too so it's not just a plotting isssue. Although I guess results are better overall for everything else so maybe we address it in a future PR ? 

sdss-classification-acc

**Comment by ismael-mendoza** [comment]
After discussing, we realized that results are overall improved for classification of all galaxies (jump from 0.4 to 0.75) so we will go ahead and merge. We will look at the classification issue for bright galaxies in a separate issue.

**Pull request merged**
