### PR TITLE
Misc Changes

### PR DESCRIPTION
**Pull request by ismael-mendoza**
Some small errors I noticed while working on the EECS 545 project last semester but never got pushed until now. 

@jeff-regier , quick question - should the `poetry.lock` file be committed? I figured that as long as everyone has the correct `pyproject.toml` that should be sufficient (since if this file changes then the `.lock` file will be updated automatically after running `poetry lock` or `poetry update`). What do you think?

### CODE REVIEW

**Comment by jeff-regier** [comment]
I'm not sure what the standard practice is.
If we commit `poetry.lock` to version control, then, say, six months from now, we'll be able to checkout a version of bliss from today and run it easily, even though many dependencies will have made breaking changes by then.
But there are probably some drawbacks too, e.g. large diffs, having to run `poetry install` every time some else changes poetry.lock.

**Comment by jeff-regier** [comment]
After reading a bit about it, I think committing `poetry.lock` is better than not. But we should try not to update it all the time without reason. A good reason would be that we have a new dependency to add. Or we need a newer version. Or that it's been awhile and many dependencies are better now.

**Comment by ismael-mendoza** [comment]
I see, in this case it seems two dependencies were updated to newer versions but both don't seem important (although not sure). In this case should we not commit then?

**Comment by jeff-regier** [comment]
Either way seems fine

**Comment by ismael-mendoza** [comment]
all tests pass and gpu and cpu now

**Pull request merged**
