### PR TITLE
Fix matching algorithm by adding sharp penalty for points far away

### LINKED ISSUE #518: `linear_sum_assignment` can lead to incorrect matches
I was digging into some recall/precision metrics again, and I realized that the `linear_sum_assignment` function might be leading to some unintuitive matching. This could be causing the bug that @ismael-mendoza showed last week with Plotly, and might be causing us to look worse on recall/precision metrics.

 `linear_sum_assignment` minimizes the total sum of distances between matched points, but this isn't really what we want. Here's an example:
image

Match 1 matches the objects which are within "matching distance" (1), but has a higher cost than the optimal solution Match 2, which yields no matches.

### PR DESCRIPTION
**Pull request by dereklhansen**
Fixes #518.

### CODE REVIEW

**Comment by dereklhansen** [comment]
This PR fixes the issue I was seeing in the recall/precision numbers. @ismael-mendoza Can you check your plotly script and see if this fixes the issue you were showing us last Wednesday?

**Comment by dereklhansen** [comment]
On my end the recall and precision numbers are slightly improved:
image

**Review by ismael-mendoza — APPROVED** [review]
This makes sense @dereklhansen - thanks for looking into this more. I'll check my plotly script and post the results below.

**Comment by ismael-mendoza** [comment]
Yeah it seems like all the mismatches/matches in plotly make sense now too! The examples i had looked at from the last meeting now make sense

**Pull request merged**
