### PR TITLE
Uploading temporary baseline model supporting 5D input, 3D conv

### PR DESCRIPTION
**Pull request by sawanp813**
This PR uploads a temporary baseline model supporting 5D input with 3D convolutions. The only transform it takes is a `log_transform` of the background-subtracted image.

### CODE REVIEW

**Review by jeff-regier — APPROVED** [review]
Why isn't this part of #882?

**Comment by sawanp813** [comment]
> Why isn't this part of #882?

If it wasn't separate then we wouldn't be able to have the API tests passing - same issue that we had with the end-to-end encoder PR a while back.

**Comment by jeff-regier** [comment]
I thought the mocking/monkeypatch stuff took care of that? Which test is it that's problematic?

**Comment by sawanp813** [comment]
> 

I can verify that with @zhixiangteoh and open an issue if that's still the case.

**Comment by jeff-regier** [comment]
I see, in that case, please try to do it all in #882. If it's a problem, we should open an issue about the dependence between branches.

**Pull request closed without merging**
