### PR TITLE
Utilize square-root of background when log-transforming images

### LINKED ISSUE #450: Replace 100 with sqrt(background)*4 in `subtract_bg_and_log_transform`

### PR DESCRIPTION
**Pull request by dereklhansen**
Closes #450.

### CODE REVIEW

**Comment by dereklhansen** [comment]
image

**Comment by dereklhansen** [comment]
Quite a boost in performance with this change on real data.

**Comment by ismael-mendoza** [comment]
That's impressive and surprising, I would've guess that we would get more false positives

**Comment by ismael-mendoza** [comment]
Quick question, did you retrain the binary / location encoder after changing this function? This should also affect their training right?

**Comment by jeff-regier** [comment]
If the particular image normalization procedure we apply makes such a difference, perhaps we should apply multiple different normalization procedures (e.g., one that subtracts 4 sds, one that subtracts 3.4 sds), stack the normalized images (one channel each), and pass the whole stack to the location autoencoder. It may help to dedicate two input channels to the background and the unnormalized image too, in case the location autoencoder can figure out how to make use of them.

**Pull request merged**
