### PR TITLE
Reduce predict tests

### LINKED ISSUE #876: pytest is slow again
It's taking 30 minutes to run the tests twice (once on the GPU, once on the CPU).

Longest running tests:
```

343.11s call     tests/test_predict.py::TestPredict::test_predict_decals_multiple_bricks
190.70s call     tests/test_predict.py::TestPredict::test_predict_decals
100.79s call     tests/test_predict.py::TestPredict::test_predict_sdss_multiple_rcfs
50.48s call     tests/test_predict.py::TestPredict::test_predict_sdss
50.28s call     tests/test_predict.py::TestPredict::test_predict_sdss_single_band
32.87s setup    tests/test_metrics.py::TestMetrics::test_photo_self_agreement
```

We may also want to use the [jobs.<job_id>.steps[*].timeout-minutes](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes) setting to limit pytest runtime to 5 or 10 minutes.

### PR DESCRIPTION
**Pull request by zhixiangteoh**
Remove tests that test mostly already-tested code.

Fixes #876.

### CODE REVIEW

**Comment by jeff-regier** [comment]
Looks like the tests are still taking > 20 minutes, with ~12 minutes consumed `test_predict_decals_multiple_bricks` alone. (And another 3 minutes consumed by `test_predict_sdss_multiple_rcfs`.

Could we some configuration options to run with just subimages within bricks/fields. i.e., for each brick/field, process just on a region (perhaps an 80x80-pixel box) specified in the config? This could be useful for users too, not just for testing. Users may only be image in a particular bounding box.

```
384.15s call     tests/test_predict.py::TestPredict::test_predict_decals_multiple_bricks
99.43s call     tests/test_predict.py::TestPredict::test_predict_sdss_multiple_rcfs
```

**Review by jeff-regier — CHANGES_REQUESTED** [review]
Definitely an improvement, but I still hope we can get runtime below 10 minutes--see comment above.

**Comment by zhixiangteoh** [comment]
> Looks like the tests are still taking > 20 minutes, with ~12 minutes consumed `test_predict_decals_multiple_bricks` alone. (And another 3 minutes consumed by `test_predict_sdss_multiple_rcfs`.)
> 
> Could we add some (optional) configuration settings to process just subimages within bricks/fields. i.e., for each brick/field, process just on a region (perhaps an 80x80-pixel box) specified in the config? This could be useful for users too, not just for testing. Users may only be interested in a particular bounding box.
> 
> ```
> 384.15s call     tests/test_predict.py::TestPredict::test_predict_decals_multiple_bricks
> 99.43s call     tests/test_predict.py::TestPredict::test_predict_sdss_multiple_rcfs
> ```

Predictions are already being done on 160x160 pixel box (`testing_config.predict.crop.width|height`), and profiling shows that 80x80 doesn't cut runtime much. Overriding `align` now which cuts a chunk of time.

**Review by jeff-regier — APPROVED** [review]
Excellent! Test finish in 8 minutes with no drop in test coverage.

**Pull request merged**
