### PR TITLE
Generate Sphinx Docs automatically with Github Actions

### LINKED ISSUE #340: Github action to rebuild documentation
I always forget to rebuild the documentation whenever I push, might it be good to have a github action that does it automatically at every push to master?

### PR DESCRIPTION
**Pull request by dereklhansen**
Closes #340.

### CODE REVIEW

**Comment by dereklhansen** [comment]
@jeff-regier Can you change the settings to point the Github pages to the "master-sphinx" for documentation?

**Comment by dereklhansen** [comment]
The action successfully builds the documentation and places it into the "master-sphinx" branch. I'm going to delete the part that triggers on pull request now so it will only happen on commits to master.

**Comment by jeff-regier** [comment]
Derek, I just made you an admin for the bliss repo. Will you make the change?

**Comment by dereklhansen** [comment]
> Derek, I just made you an admin for the bliss repo. Will you make the change?

Yes, I was able to make the change. Thank you!

**Comment by dereklhansen** [comment]
This will also close #350 by adding a button to the readme.

**Pull request merged**
